blog/urls.py
from django.urls import path
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'myblog'

urlpatterns = [
    path('myblog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('myblog/list/', BlogListView.as_view(), name='blogs_list'),
    path('myblog/detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('myblog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('myblog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    content = models.TextField(verbose_name='содержимое', blank=True, null=True)
    preview = models.ImageField(upload_to='blog/image', verbose_name='изображение', blank=True, null=True)
    created_at = models.DateField(verbose_name='дата создания', auto_now_add=True)
    publication_sign = models.BooleanField(verbose_name='признак публикации')
    number_of_views = models.IntegerField(verbose_name='колличество просмотров', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ['title', 'created_at', 'number_of_views']

blog/views.py
from django.db.models import F

from .models import Blog
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'content', 'preview', 'publication_sign']
    template_name = 'blog/blog_form.html'
    context_object_name = 'blog'
    success_url = reverse_lazy('myblog:blogs_list')


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blogs_list.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(publication_sign=True)


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    context_object_name = 'blog'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        Blog.objects.filter(pk=obj.pk).update(number_of_views=F('number_of_views') + 1)
        obj.number_of_views += 1
        return obj


class BlogUpdateView(UpdateView):
    model = Blog
    template_name = 'blog/blog_form.html'
    fields = ['content', 'publication_sign', 'title', 'preview']
    success_url = reverse_lazy('myblog:blogs_list')


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blog/blog_confirm_delete.html'
    success_url = reverse_lazy('myblog:blogs_list')

blog/templates/blog/base.html
<!doctype html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<title>{% block title %} MyBlog {% endblock %}</title>
{% include 'blog/header.html' %}
<body>
{% block content %}
{% endblock %}
</body>
{% include 'blog/footer.html' %}
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}
{% block title %}Удалить пост{% endblock %}
{% block content %}
<div class="container">
    <h2>Удалить пост</h2>
    <p>Вы уверены, что хотите удалить "{{ blog.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'myblog:blogs_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% block title %}Детали поста{% endblock %}
{% block content %}
<div class="container">
    <h2>{{ blog.title }}</h2>
    <p>Контент: {{ blog.content }}</p>
    <p>Дата публикации: {{ blog.created_at|date:"d M Y" }}</p>
    <p>Колличество просмотров: {{ blog.number_of_views }}</p>
    <p>ID: {{ blog.pk }}</p>
    <a href="{% url 'myblog:blog_create' %}" class="btn btn-secondary">Редактировать</a>
    <a href="{% url 'myblog:blog_delete' blog.pk %}" class="btn btn-danger">Удалить</a>
    <a href="{% url 'myblog:blogs_list' %}" class="btn btn-primary">Вернуться к списку</a>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}
{% block title %}Create post{% endblock %}
{% block content %}
<form method="post" class="container">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Создать</button>
    <a href="{% url 'myblog:blogs_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% block title %}Список постов{% endblock %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Список постов</h1>
</div>
<a href="{% url 'myblog:blog_create' %}" class="btn btn-primary mb-3">Создать новый объект</a>
<ul class="list-group">
    {% for blog in blogs %}
    <li class="list-group-item">
        <a href="{% url 'myblog:blog_detail' blog.pk %}">{{ blog.title }}</a>
        <a href="{% url 'myblog:blog_update' blog.pk %}" class="btn btn-sm btn-secondary ml-3">Редактировать</a>
        <a href="{% url 'myblog:blog_delete' blog.pk %}" class="btn btn-sm btn-danger ml-1">Удалить</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

blog/templates/blog/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            MyBlog
            <small class="d-block mb-3 text-muted">&copy; 2025</small>
        </div>
    </div>
</footer>

blog/templates/blog/header.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>