blog/urls.py
from django.urls import path
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'myblog'

urlpatterns = [
    path('myblog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('myblog/list/', BlogListView.as_view(), name='blogs_list'),
    path('myblog/detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('myblog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('myblog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import CatalogConfig
from .views import ProductListView, ProductDetailView, ProductTemplateView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, Category3ListView, Category4ListView

app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/', ProductTemplateView.as_view(), name='contacts'),
    path('product_detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('home/', ProductListView.as_view(), name='product_list'),
    path('form/', ProductCreateView.as_view(), name='product_form'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('category_3_list/', Category3ListView.as_view(), name='category_3_list'),
    path('category_4_list/', Category4ListView.as_view(), name = 'category_4_list'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from .views import RegisterView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='catalog:product_list'), name='logout'),
]

catalog/models.py
from users.models import CustomUser
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(verbose_name='описание категории', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ['name']


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='название продукта')
    description = models.TextField(verbose_name='описание продукта', blank=True, null=True)
    image = models.ImageField(upload_to='catalog/photo', verbose_name='изображение', blank=True, null=True)
    price = models.IntegerField(verbose_name='цена за покупку')
    created_at = models.DateField(verbose_name='дата создания', auto_now_add=True)
    updated_at = models.DateField(verbose_name='дата последнего изменения', auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    publication_status = models.BooleanField(default=False, verbose_name='статус публикации')
    owner = models.ForeignKey(CustomUser, verbose_name='владелец продукта', blank=True, null=True,
                              on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ['name', 'price', 'created_at', 'category']
        permissions = [
            ('can_unpublish_product', 'Can unpublish product'),
        ]

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Product
from catalog import constanta


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'image', 'price', 'category', 'publication_status']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите название продукта'
        })

        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите описание продукта'
        })

        self.fields['image'].widget.attrs.update({
            'class': 'form-control',
            'type': 'image'
        })

        self.fields['price'].widget.attrs.update({
            'class': 'form-control',
            'type': 'integer'
        })

        self.fields['category'].widget.attrs.update({
            'class': 'form-control'
        })

    def clean_name(self):
        block_list = constanta.BLOCK_LIST
        name = self.cleaned_data.get('name')
        if name.lower() in block_list:
            raise ValidationError('Имя имеет запрещенное слово')
        return name

    def clean_description(self):
        block_list = constanta.BLOCK_LIST
        description = self.cleaned_data.get('description')
        if description.lower() in block_list:
            raise ValidationError('Описание имеет запрещенное слово')
        return description

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price < 0:
            raise ValidationError('Цена введена неправильно')
        return price


class ProductModeratorForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['publication_status']

catalog/views.py
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import ProductForm, ProductModeratorForm
from .models import Product, Category
from .services import ProductService


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:product_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm('can_unpublish_product'):
            return ProductModeratorForm
        raise PermissionDenied


@method_decorator(cache_page(60 * 15), name='dispatch')
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    template_name = 'catalog/product_confirm_delete.html'
    success_url = reverse_lazy('catalog:product_list')

    def test_func(self):
        user = self.request.user
        return user == self.object.owner or user.has_perm('can_delete_product')


class ProductTemplateView(TemplateView):
    model = Product
    template_name = "catalog/contacts.html"


class Category3ListView(ListView):
    model = Category
    template_name = "catalog/category_3_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = '3'
        context['product_list'] = ProductService.get_category_list(category_id)
        return context


class Category4ListView(ListView):
    model = Category
    template_name = "catalog/category_4_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = '4'
        context['product_list'] = ProductService.get_category_list(category_id)
        return context

catalog/templates/catalog/base.html
<!doctype html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<title>{% block title %} Skystore {% endblock %}</title>
{% include 'catalog/header.html' %}
<body>
{% block content %}
{% endblock %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
{% include 'catalog/footer.html' %}
</html>

catalog/templates/catalog/category_3_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Техника</h1>
</div>
<div class="card mb-4 box-shadow">
    {% for product in product_list %}
    <div class="card-group">
        <div class="card">
            <img src="{{ media | image_filter }}">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text"><small class="text-body-secondary">Last updated {{ product.updated_at|date:'d M Y' }}</small></p>
                <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-primary">Подробнее</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/category_4_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Товары для детей</h1>
</div>
<div class="card mb-4 box-shadow">
    {% for product in product_list %}
    <div class="card-group">
        <div class="card">
            <img src="{{ media | image_filter }}">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text"><small class="text-body-secondary">Last updated {{ product.updated_at|date:'d M Y' }}</small></p>
                <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-primary">Подробнее</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block title %}Контакты{% endblock %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2025</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

catalog/templates/catalog/header.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_form' %}">Создать продукт</a>
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown"
                    aria-expanded="false">
                Категории
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'catalog:category_3_list' %}">Техника</a></li>
                <li><a class="dropdown-item" href="{% url 'catalog:category_4_list' %}">Товары для детей</a></li>
            </ul>
        </div>
        {% if user.is_authenticated %}
        <form method="post" action="{% url 'users:logout' %}" style="display: inline">
            {% csrf_token %}
            <button type="submit" class="p-2 btn btn-outline-danger">Выйти</button>
        </form>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
        {% endif %}
    </nav>
</div>

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
</div>
<div class="card mb-4 box-shadow">
    {% for product in products %}
    <div class="card-group">
        <div class="card">
            <img src="{{ product.image | media_filter }}">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text"><small class="text-body-secondary">Last updated {{ product.updated_at|date:'d M Y' }}</small></p>
                <a href="{% url 'catalog:product' product.pk %}" class="btn btn-primary">Подробнее</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block title %}Удалить продукт{% endblock %}
{% block content %}
<div class="container">
    <h2>Удалить продукт</h2>
    <p>Вы уверены, что хотите удалить "{{ product.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block title %}Детали продукта{% endblock %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Детали продукта</h1>
</div>
<div class="container mt-5">
    <img src="{{ product.image | image_filter }}">
    <h2>{{ product.name }}</h2>
    <p>Категория: {{ product.category }}</p>
    <p>Описание: {{ product.description|truncatechars:100 }}</p>
    <p>Цена: {{ product.price }}</p>
    <p>Дата создания: {{ product.created_at|date:"d M Y" }}</p>
    <p>Дата обновления: {{ product.updated_at|date:"d M Y" }}</p>
    <p>Статус публикации: {{ product.publication_status }}</p>
    <p>Владелец: {{ product.owner }}</p>
    <a href="{% url 'catalog:product_list' %}" class="btn btn-primary">Вернуться в каталог</a>
    {% if perms.product.can_unpublish_product and perms.product.can_delete_product or user == product.owner %}
    <a href="{% url 'catalog:product_update' product.pk %}" class="btn btn-secondary">Редактировать</a>
    <a href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-danger">Удалить</a>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block title %}Create product{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Создать</button>
    <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
</div>
<div class="card mb-4 box-shadow">
    {% for product in products %}
    <div class="card-group">
        <div class="card">
            <img src="{{ image | image_filter }}">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text"><small class="text-body-secondary">Last updated {{ product.updated_at|date:'d M Y' }}</small></p>
                <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-primary">Подробнее</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}